### PR TITLE
Share the love with Mac users

### PR DESCRIPTION
**Pull request by ndouglas**
Hey!  I just checked this out and ~wrote~ copied and pasted a couple tests for my ROM.  I'm the designated Test Sap on my team, so I hope I'll be able to contribute to this project 🙂

### CODE REVIEW

**Comment by potatolain** [comment]
Hey there! I really appreciate your interest in the project. Mac os support is actually something I'd really like to add! 

Unfortunately, I don't think it's quite this simple - most of the functionality of the tool relies on being able to use [Mesen](https://mesen.ca/) to run the rom/tests. As far as I know Mesen isn't able to run on macs, so that functionality would be broken. (Please correct me if you know of a way!) 

If you're only interested in the behavior in [NesRomFile](https://cppchriscpp.github.io/nes-test/NesRomFile.html) I suppose this would work, though there are some additional documentation+errors I'd want to add to make it obvious what is available on macs. 

I hope this doesn't burst your bubble - I'm really excited to see people start using this!

**Comment by ndouglas** [comment]
well, crap

tumblr_42e90087fcbd73ba496a459b2c55414b_e209ef80_400

But thanks for your fast response!

I was actually thinking about writing a simple NES emulator to run tests -- nothing fancy, really, just something that was able to poke some inputs and read values from memory addresses.  That was before I found your project.  Maybe it's worth pondering further.

I'll take a peek at Mesen here -- my C++ days are >10 years in the past, so I'm not expecting much.

**Comment by potatolain** [comment]
Dang, gotta admit, I wasn't expecting that kind of interest. In that case, here's what else I know - it's been discussed a few times and in theory should be easy, but in practice seems to not be. 

The main problem seems to be the ui - which we don't really care about for this tool, so there might be a way to hack that stuff out of the way. There's also apparently [a libretro core](https://forums.libretro.com/t/mesen-core/14124) which might [work on mac](https://github.com/SourMesen/Mesen/issues/306) -- I'm not sure if that might open some doors for us, I actually only just found out about it today.

Other references:

* [recent Mesen-X issue](https://github.com/NovaSquirrel/Mesen-X/issues/36) - sounds like it's being rewritten with a new UI; I've been kinda hoping for that to be honest
* [main discussion on it](https://github.com/SourMesen/Mesen/issues/123) - it's pretty short but goes into the challenges a bit
* [Some posts on nesdev recommending wine](https://forums.nesdev.org/viewtopic.php?p=225891&sid=28d57c69b91d14ccbddf4325296b4226#p225891) -- I haven't explored this option at all, but if it runs, I can probably add support (and show a little message saying "hey I need wine, here's how to install it" if the wine binary isn't on the system)

**Comment by ndouglas** [comment]
>in practice seems to not be

I'll take everyone's word for it, then 😩  Given what you've said and that the original repo is archived I'll take all of this as a hint to back away slowly, lol.

I think I'm going to poke my nose into writing an emulator with this very specific use case in mind.  I'm writing my first (and almost certainly only) ROM, so it seemed like two compatible projects.  Obv IDK if it'll be useful more widely.  Maybe it won't be useful to anyone who's not following the Nerdy Nights tutorial, etc.  

I'll close this PR for now and I'll try to drop back by around August 15, if not earlier.  Hopefully I'll have something interesting to share.  If there's only an embarrassed silence, it's because real life got in the way or I noped out after realizing what I was up against, lol.

**Comment by potatolain** [comment]
Best of luck! That sounds like a really interesting project, it'd be cool to see for sure. 

This did get me to try one more time for mac support, but unfortunately no dice. For my own reference, the things I tried: 
* Mono by itself, using --testrunner to try to bypass ui creation - no dice, even with settings.xml it seems to really want to show some random dialog. If I could just make it stop that...
* PlayOnMac - trying to run mesen seems to run into a problem installing XQuartz, where it hangs for at least 20-30 minutes
  * Skipping playonmac binary to use wine: can't find mono 
* wineskin - couldn't figure out how to run it without building a full wrapper, which I explicitly do not want to do (and even then it wasn't straightforward)

Unfortunately apple's habit of removing features very quickly has a way of biting developers a lot. I want to like mac os, but every time I try to build anything, it's endless frustration.

At this point I think my best bet, short of switching emulators, is to create a customized headless mesen with all the forms stuff removed. Which seems, painful.

**Pull request closed without merging**
